-- ELIMINAR Y CREAR BASE DE DATOS
DROP DATABASE IF EXISTS BODEGAS_DB;
CREATE DATABASE BODEGAS_DB;
USE BODEGAS_DB;

-- TABLA DE USUARIOS
CREATE TABLE USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);

-- TABLA DE ROLES
CREATE TABLE ROL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

-- TABLA INTERMEDIA USUARIO_ROL
CREATE TABLE USUARIO_ROL (
    USUARIO_ID BIGINT,
    ROL_ID BIGINT,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON DELETE CASCADE
);

-- INSERTAR ROLES DISPONIBLES
INSERT INTO ROL (ID, NOMBRE) VALUES (1, 'USER');
INSERT INTO ROL (ID, NOMBRE) VALUES (2, 'ADMIN');

-- INSERTAR USUARIOS DE EJEMPLO (CONTRASEÑA ENCRIPTADA CON BCRYPT)
INSERT INTO USUARIO (NOMBRE, CORREO, USERNAME, PASSWORD)
VALUES ('Josue Usuario', 'josue@email.com', 'josue', '$2a$10$xa...');

INSERT INTO USUARIO (NOMBRE, CORREO, USERNAME, PASSWORD)
VALUES ('Administrador General', 'admin@email.com', 'admin', '$2a$10$xaaReEFEh8.ulnY5QIKwFeTnaWcLmY7Zc128wdKq3jcOjcer1Sf92');

-- ASIGNAR ROLES A LOS USUARIOS
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1, 1); -- Josue → USER
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (2, 2); -- Admin → ADMIN

-- CONSULTA DE PRUEBA (OPCIONAL)
SELECT ID, NOMBRE, USERNAME, CORREO , password FROM USUARIO WHERE USERNAME = 'josue';
