-- ELIMINAR BASE Y USUARIO SI EXISTEN
DROP DATABASE IF EXISTS BODEGAS_DB;
DROP USER IF EXISTS 'usuario_bodega'@'%';

-- CREAR BASE Y USUARIO
CREATE DATABASE BODEGAS_DB;
CREATE USER 'usuario_bodega'@'%' IDENTIFIED BY 'Clave_Bodega123.';
GRANT ALL PRIVILEGES ON BODEGAS_DB.* TO 'usuario_bodega'@'%';
FLUSH PRIVILEGES;

-- USAR BASE DE DATOS
USE BODEGAS_DB;

-- TABLA USUARIO
CREATE TABLE USUARIO (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    CORREO VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL
);

-- TABLA ROL
CREATE TABLE ROL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);

-- TABLA INTERMEDIA USUARIO_ROL
CREATE TABLE USUARIO_ROL (
    USUARIO_ID BIGINT,
    ROL_ID BIGINT,
    PRIMARY KEY (USUARIO_ID, ROL_ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID) ON DELETE CASCADE
);

-- ROLES
INSERT INTO ROL (ID, NOMBRE) VALUES (1, 'USER');
INSERT INTO ROL (ID, NOMBRE) VALUES (2, 'ADMIN');

-- USUARIOS DE EJEMPLO
INSERT INTO USUARIO (NOMBRE, CORREO, USERNAME, PASSWORD)
VALUES ('Josue Usuario', 'josue@email.com', 'josue', '$2a$10$xa...');

INSERT INTO USUARIO (NOMBRE, CORREO, USERNAME, PASSWORD)
VALUES ('Administrador General', 'admin@email.com', 'admin', '$2a$10$xaaReEFEh8.ulnY5QIKwFeTnaWcLmY7Zc128wdKq3jcOjcer1Sf92');

-- RELACIÓN USUARIO/ROL
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (1, 1);
INSERT INTO USUARIO_ROL (USUARIO_ID, ROL_ID) VALUES (2, 2);
